# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
    - vote/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '2623254d-fb29-4824-b5fe-390c0fbaf6b1'
  imageRepository: 'votingapp'
  containerRegistry: 'akhileshazcicd.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: 'azureagent'

stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'vote/Dockerfile'
        tags: '$(tag)'
- stage: Push
  displayName: Push 
  jobs:
  - job: Push
    displayName: Push to ACR
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'

- stage: Update
  displayName: update 
  jobs:
  - job: Update
    displayName: Update Manifest
    steps:
    
    - task: Bash@3
      displayName: Fix shell script line endings
      inputs:
        targetType: 'inline'
        script: |
          sed -i 's/\r$//' scripts/updateK8sManifest.sh
          chmod +x scripts/updateK8sManifest.sh
    - task: ShellScript@2
      inputs:
        scriptPath: 'scripts/updateK8sManifest.sh'
        args: 'vote $(imageRepository) $(tag)'
